#!/usr/bin/env bash
# Local dev: pull the deployed resource ids out of Terraform state, write
# web/config.js, and serve the site on http://localhost:5173 (an origin the
# API's CORS config already allows).
#
# Requires: terraform, python3. No npm, no build step.

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root/infra"

if [[ ! -f terraform.tfstate && ! -d .terraform ]]; then
  echo "No Terraform state here. Run 'terraform init && terraform apply' in infra/ first." >&2
  exit 1
fi

read -r region user_pool client_id api <<<"$(terraform output -json | python3 -c '
import json, sys
o = json.load(sys.stdin)
print(
    o["region"]["value"],
    o["cognito_user_pool_id"]["value"],
    o["cognito_client_id"]["value"],
    o["api_endpoint"]["value"],
)')"

cat >"$root/web/config.js" <<EOF
// Generated by scripts/dev.sh for local development.
window.DRIFTLOG_CONFIG = {
  region: "$region",
  userPoolId: "$user_pool",
  clientId: "$client_id",
  apiEndpoint: "$api",
};
EOF

echo "Wrote web/config.js"
echo "Serving DriftLog at http://localhost:5173 — Ctrl+C to stop."
cd "$root/web"
exec python3 -m http.server 5173 --bind 127.0.0.1
